<?php
/**
 * Created by PhpStorm.
 * User: candelariajr
 * Date: 1/25/2017
 * Time: 8:21 AM
 */

updateData();
/**
 * Auto-invoke function that starts the process of updating the database
 */
function updateData(){
    $submittedSQL = "";
    //if no id is submitted, then create from
    if(isset($_GET['id'])){
        $submittedSQL = generateUpdateSQL();
    }else
        $submittedSQL = generateInsertSQL();
    update($submittedSQL);
}
/*
 *
 * SQL GERNRATION CODE
 *
 * */
/**
 * @return string
 *  Returns the SQL generated by processing the data sent to the server in an AJAX request
 */
function generateUpdateSQL(){
    $sql = "UPDATE compstatus SET "; //The rest of the SQL is concat to this
    $index = 0;
    $updateCount = 0;
    foreach($_GET as$key => $value){
        if($value != "null"){
            $updateCount++;
        }
    }
    $notInts = array("computer_name","computer_type","table_name");
    foreach($_GET as $key => $value){
        if($value != "null" && $key != "id"){
            if(--$updateCount != 1){
                $sql.= $key." ";
                $sql.= in_array($key, $notInts) ? " = '".sanitizeAlphaNum($value)."' " : "= ".sanitizeInt($value).", ";
            }else{
                $sql.= $key." ";
                $sql.= in_array($key, $notInts) ? " = '".sanitizeAlphaNum($value)."' " : "= ".sanitizeInt($value)." ";
            }
            $index++;
        }
    }
    $sql.=" WHERE id = ".sanitizeInt($_GET['id']);
    //DEBUG: Uncommenting this line results in the SQL being output to the modal dialog. Used
    //by me for troubleshooting.
    echo("$sql<br>");
    return $sql;
}

function generateInsertSQL(){
    $sql = "INSERT INTO compstatus (computer_name, computer_type, table_name, floor, seat, left_pos, top_pos, is_public, is_excluded, is_pilot, is_dedicated) VALUES ("; //The rest of the SQL is concat to this
    $sql.= "'".sanitizeAlphaNum($_GET['computer_name'])."', ";
    $sql.= "'".sanitizeAlphaNum($_GET['computer_type'])."', ";
    $sql.= "'".sanitizeAlphaNum($_GET['table_name'])."', ";
    $sql.= sanitizeInt($_GET['floor']).", ";
    $sql.= sanitizeInt($_GET['seat']).", ";
    $sql.= sanitizeInt($_GET['left_pos']).", ";
    $sql.= sanitizeInt($_GET['top_pos']).", ";
    $sql.= sanitizeInt($_GET['is_public']).", ";
    $sql.= sanitizeInt($_GET['is_excluded']).", ";
    $sql.= sanitizeInt($_GET['is_pilot']).", ";
    $sql.= sanitizeInt($_GET['is_dedicated']);
    $sql.=");";
    //DEBUG: Uncommenting this line results in the SQL being output to the modal dialog. Used
    //by me for troubleshooting.
    echo("$sql<br>");
    return "";
}

/**
 * @param $intValue
 *  The input to be scrubbed. generateSQL() calls this when a name for a key of non-integers
 *  doesn't find the key in the list, passing the argument of the value associated with the key
 * @return mixed
 *  Scrubbed....All non numerals removed from input
 */
function sanitizeInt($intValue){
    return preg_replace("/[^0-9]/", "", $intValue);
}

/**
 * @param $alphaValue
 *  The input to be scrubbed. generateSQL() calls this when a name for a key of non-integers
 *  finds the key in the list, passing the argument of the value associated with the key
 * @return mixed
 *  Scrubbed....All non alphanumerics and unapproved symbols removed from input
 */
function sanitizeAlphaNum($alphaValue){
    return preg_replace("/[();']/", "", $alphaValue);
}
/*
 *
 * END SQL GERNRATION CODE
 *
 * */



/*
 *
 * DB HANDLER
 *
 * */
/**
 * @param $queryString
 *  given query.
 * This takes the query, builds the connection to the database using params as specified
 * within dbauth.php.
 * Success or failure is returned to the echo which puts it in the modal form on the AJAX callback.
 */
function update($queryString){
    $server = "";
    $user = "";
    $password = "";
    $database = "";
    require("dbauth.php");
    $conn = new mysqli($server, $user, $password, $database);
    if(mysqli_connect_errno()){
        echo "CANT CONNECT TO DB! Your changes haven't been saved!";
    }
    echo (mysqli_query($conn, $queryString)) ? "Update Successful" : "Update Failed!";
    mysqli_close($conn);
}
/*
 *
 * END DB HANDLER
 *
 * */

