<?php
/**
 * Created by PhpStorm.
 * User: candelariajr
 * Date: 1/25/2017
 * Time: 8:21 AM
 */

//If you enable this, you will get RAW SQL output as well as GET/POST data, etc output to the screen.
//Do NOT use in production
$debug = false;
updateData();
/**
 * Auto-invoke function that starts the process of updating the database
 */
function updateData(){
    $submittedSQL = "";
    //if no id is submitted, then create from
    if(isset($_GET['id'])){
        $submittedSQL = generateUpdateSQL();
    }else
        $submittedSQL = generateInsertSQL();
    update($submittedSQL);
}
/*
 *
 * SQL GENERATION CODE
 *
 * */
/**
 * @return string
 *  Returns the SQL generated by processing the data sent to the server in an AJAX request
 */
function generateUpdateSQL(){
    $sql = "UPDATE compstatus SET "; //The rest of the SQL is concat to this
    $index = 0;
    $updateCount = 0;
    foreach($_GET as$key => $value){
        if($value != "null"){
            $updateCount++;
        }
    }
    $updateCount--;
    $notInts = array("computer_name","computer_type","table_name");
    foreach($_GET as $key => $value){
        if($value != "null" && $key != "id"){
            if(--$updateCount != 0){
                $sql.= $key." ";
                $sql.= in_array($key, $notInts) ? " = '".sanitizeAlphaNum($value)."', " : "= ".sanitizeInt($value).", ";
            }else{
                $sql.= $key." ";
                $sql.= in_array($key, $notInts) ? " = '".sanitizeAlphaNum($value)."' " : "= ".sanitizeInt($value)." ";
            }
            $index++;
        }
    }
    $sql.=" WHERE id = ".sanitizeInt($_GET['id']);

    GLOBAL $debug;
    if($debug){
        echo("$sql<br>");
        printGet();
    }
    if(!uniqueCompName(sanitizeAlphaNum($_GET['computer_name']))){
        $sql = "";
    }
    return $sql;
}

function generateInsertSQL(){
    $sql = "INSERT INTO compstatus (computer_name, computer_type, table_name, floor, seat, left_pos, top_pos, is_public, is_excluded, is_pilot, is_dedicated) VALUES ("; //The rest of the SQL is concat to this
    $sql.= "'".sanitizeAlphaNum($_GET['computer_name'])."', ";
    $sql.= "'".sanitizeAlphaNum($_GET['computer_type'])."', ";
    $sql.= "'".sanitizeAlphaNum($_GET['table_name'])."', ";
    $sql.= sanitizeInt($_GET['floor']).", ";
    $sql.= sanitizeInt($_GET['seat']).", ";
    $sql.= sanitizeInt($_GET['left_pos']).", ";
    $sql.= sanitizeInt($_GET['top_pos']).", ";
    $sql.= sanitizeInt($_GET['is_public']).", ";
    $sql.= sanitizeInt($_GET['is_excluded']).", ";
    $sql.= sanitizeInt($_GET['is_pilot']).", ";
    $sql.= sanitizeInt($_GET['is_dedicated']);
    $sql.=");";

    GLOBAL $debug;
    if($debug){
        echo("$sql<br>");
        printGet();
    }
    if(!uniqueCompName(sanitizeAlphaNum($_GET['computer_name']))){
        $sql = "";
    }
    return $sql;
}

/**
 * @param $intValue
 *  The input to be scrubbed. generateSQL() calls this when a name for a key of non-integers
 *  doesn't find the key in the list, passing the argument of the value associated with the key
 * @return mixed
 *  Scrubbed....All non numerals removed from input
 */
function sanitizeInt($intValue){
    return preg_replace("/[^0-9]/", "", $intValue);
}

/**
 * @param $alphaValue
 *  The input to be scrubbed. generateSQL() calls this when a name for a key of non-integers
 *  finds the key in the list, passing the argument of the value associated with the key
 * @return mixed
 *  Scrubbed....All non alphanumerics and unapproved symbols removed from input
 */
function sanitizeAlphaNum($alphaValue){
    return preg_replace("/[();']/", "", $alphaValue);
}
/*
 *
 * END SQL GERNRATION CODE
 *
 * */



/*
 *
 * DB HANDLER
 *
 * */
/**
 * @param $queryString
 *  given query.
 * This takes the query, builds the connection to the database using params as specified
 * within dbauth.php.
 * Success or failure is returned to the echo which puts it in the modal form on the AJAX callback.
 */
function update($queryString){
    $server = "";
    $user = "";
    $password = "";
    $database = "";
    require("dbauth.php");
    $conn = new mysqli($server, $user, $password, $database);
    if(mysqli_connect_errno()){
        echo "CANT CONNECT TO DB! Your changes haven't been saved!";
    }
    if($queryString != ""){
        echo (mysqli_query($conn, $queryString)) ? "Update Successful" : "Update Failed! <br>Note: editing of coordinates has been temporarily disabled";
        mysqli_close($conn);
    }else{
        echo "Query was rejected by server. Make sure this isn't a duplicate computer name or use of a disabled editing feature.";
    }

}
/*
 *
 * END DB HANDLER
 *
 * */

/**
 * Prints all get variables. This is for debugging
 */
function printGet(){
    foreach($_GET as $key => $value)
    {
        echo 'Key = ' . $key;
        echo 'Value= ' . $value . '<br>';
    }
}

function uniqueCompName($computerName){
    $server = "";
    $user = "";
    $password = "";
    $database = "";
    require("dbauth.php");
    $conn = new mysqli($server, $user, $password, $database);
    if(mysqli_connect_errno()){
        echo "CANT CONNECT TO DB!";
    }
    $queryString = "SELECT COUNT(*) AS NAME_COUNT FROM compstatus WHERE Computer_name = '".sanitizeAlphaNum($computerName)."';";
    $results = $conn->query($queryString);
    if($results->num_rows == 1){
        $row = $results->fetch_assoc();
        if($row['NAME_COUNT'] > 0 ){
            echo "ComputerName already present!";
            return false;
        }
        else{
            return true;
        }
    }else{
        echo "SQL Generation Error: Incorrect Aggregate";
        return false;
    }
}